# Generated by Django 5.2.4 on 2025-08-16 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_eventsmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/events'),
        ),
    ]
