# Generated by Django 5.2.4 on 2025-08-02 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodmodel',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='foodmodel',
            name='price',
            field=models.IntegerField(),
        ),
    ]
