# Generated by Django 5.2.4 on 2025-08-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodmodel',
            name='image',
            field=models.ImageField(upload_to='foods/images/'),
        ),
    ]
