# Generated by Django 5.2.4 on 2025-09-12 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='offerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
                ('date', models.DateTimeField()),
                ('discount', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
