# Generated by Django 5.2.4 on 2025-09-12 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offermodel',
            name='name',
            field=models.TextField(max_length=255, unique=True),
        ),
    ]
