# Generated by Django 5.2.4 on 2025-08-15 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablemodel',
            name='seats',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='tablemodel',
            name='table_number',
            field=models.PositiveIntegerField(),
        ),
    ]
