# Generated by Django 5.2.4 on 2025-08-15 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_tablemodel_seats_alter_tablemodel_table_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablemodel',
            name='table_number',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
