# Generated by Django 5.2.4 on 2025-08-16 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_tablemodel_table_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablemodel',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
