# Generated by Django 5.2.4 on 2025-09-19 05:23

import events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50, unique=True)),
                ('descriptions', models.TextField(max_length=255)),
                ('is_happening', models.BooleanField(default=False)),
                ('event_date', models.DateTimeField(validators=[events.models.validate_event_time])),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/events')),
            ],
        ),
    ]
