# Generated by Django 5.2.4 on 2025-08-16 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventsmodel',
            name='image',
        ),
    ]
