# Generated by Django 5.2.4 on 2025-08-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_eventsmodel_event_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsmodel',
            name='event_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
