# Generated by Django 5.2.4 on 2025-09-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_eventsmodel_event_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsmodel',
            name='event_date',
            field=models.DateTimeField(),
        ),
    ]
